/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Base64;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws NoSuchAlgorithmException {
        var salt12 = getSalt();
        var salt3 = getSalt();

        var digest1 = getDigest("t", salt12);
        var digest2 = getDigest("te", salt12);
        var digest3 = getDigest("teknos", salt3);

        System.out.println("digest1: " + digest1);
        System.out.println("digest2: " + digest2);
        System.out.println("digest2: " + digest3);

    }

    public static String getDigest(String data, byte[] salt) throws NoSuchAlgorithmException {
        var dataBytes = data.getBytes();

        var messageDigest = MessageDigest.getInstance("SHA-256");

        messageDigest.update(salt);
        var digest = messageDigest.digest(dataBytes);

        var base64Encoder = Base64.getEncoder();

        return base64Encoder.encodeToString(digest);
    }

    public static byte[] getSalt() {
        var secureRandom = new SecureRandom();

        var salt = new byte[16];
        secureRandom.nextBytes(salt);

        return salt;
    }
}
