/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        HashTest classUnderTest = new HashTest();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
